language: generic

sudo: required
services:
  - docker

before_install:
  - docker build -t baasvancodeza/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true baasvancodeza/docker-react npm run test

deploy:
  provider: elasticbeanstalk
  region: "eu-west-1"
  app: "docker-react-training"
  env: "DockerReactTraining-env"
  bucket_name: "elasticbeanstalk-eu-west-1-211332116103"
  bucket_path: "docker-react-training"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KE
