language: generic

sudo: required
services:
  - docker

before_install:
  - docker build -t baasvancodeza/docker-react -f Dockerfile.dev .

script:
  - docker run baasvancodeza/docker-react npm run test -- --coverage
